apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey-app
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/dragos1993/valkey-repo-helm.git
      targetRevision: main
      path: .
      helm:
        valueFiles:
          - $values/values-dev.yaml
    - repoURL: https://github.com/dragos1993/valkey-repo-values.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: qxy2756-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
